### ISSUE TITLE
MOBroadcast not working on 1.2.5

### ISSUE THREAD

**Issue by Saraistupid** [craftycodie/OnlineModeFix#6]
The plugin isn't enabling on 1.2.5 showing this error:
```22:11:59 [INFO] [MineOnlineBroadcast] Enabling MineOnlineBroadcast v1.1.5
22:11:59 [SEVERE] Error occurred while enabling MineOnlineBroadcast v1.1.5 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/util/config/Configuration
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:235)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:37)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at gg.codie.mineonline.plugin.bukkit.MineOnlineBroadcastPlugin.initialize(MineOnlineBroadcastPlugin.java:170)
        at gg.codie.mineonline.plugin.bukkit.MineOnlineBroadcastPlugin.onEnable(MineOnlineBroadcastPlugin.java:79)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:257)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:239)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:373)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:360)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:189)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:424)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.ClassNotFoundException: org.bukkit.util.config.Configuration
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 27 more
